### PR TITLE
Fix default versioned symbol

### LINKED ISSUE #998: Binary segfaults when using `.symver` on CentOS 7
The following test program crashes (segmentation fault) when building/running on a CentOS 7 x86_64 box (with glibc 2.17, and building with gcc 12 and mold 1.10.1):

```
#include <cmath>

__asm__(".symver pow,pow@GLIBC_2.2.5");

int main(int argc, char** argv)
{
    return std::pow(10, size_t(argc));
}
```

Built with `g++ -Wall -fuse-ld=mold -o prog prog.cpp`

The binary works as expected when linking with any other linker (I tried ld.bfd, lld, and gold).

The issue disappears if I remove the `__asm__` statement.

No issue as well when building and running with mold on a Ubuntu 20.04 box.

### PR DESCRIPTION
**Pull request by ksco**
A default versioned symbol like `foo@@version` should produce `foo` and `foo@version`.

Fix #998

### CODE REVIEW

**Comment by ksco** [comment]
I'll submit a test in a separate PR later.

**Comment by ksco** [comment]
ping @rui314

**Comment by rui314** [comment]
The mapping provided by `get_symbol` is one-to-one, meaning that the there's one-to-one correspondence between symbol names passed to `get_symbol` to the returned `Symbol<E>` instance. We don't create two `Symbol<E>` instances for a single symbol name.

The DSO symbol name with the default version is an exception. It may be resolved either as `foo` or `foo@@VERSION`.

I didn't want to break the one-to-one correspondence, so the default version name is handled specially here: https://github.com/rui314/mold/blob/main/elf/passes.cc#L1229-L1244

Do you know why that code didn't work for this particular case?

**Comment by moncefmechri** [comment]
For the record, I tried the proposed patch both on the toy example in the linked issue, as well as on our large binary, and it does seem to solve the issue.

**Comment by moncefmechri** [comment]
> For the record, I tried the proposed patch both on the toy example in the linked issue, as well as on our large binary, and it does seem to solve the issue.

Let me know if there are more patches you would like me to test, happy to help.

**Comment by ksco** [comment]
> Do you know why that code didn't work for this particular case?

https://github.com/rui314/mold/blob/main/elf/input-files.cc#L1270
I think it's because a default versioned symbol will not have any version info according to the above line.

**Comment by ksco** [comment]
If we don't want to break the 1-to-1 correspondence, maybe we can add a "default version" field to `Symbol`.

**Comment by ksco** [comment]
On second thought, I think the original implementation is supposed to work, there must be something wrong. I should look into that and find the root cause.

**Comment by ksco** [comment]
In conclusion, IIUC, the original solution (i.e. [passes.cc#L1229-L1244](https://github.com/rui314/mold/blob/main/elf/passes.cc#L1229-L1244)) is not right. 

For example, `foo@v1` is declared in `a.o`, and `foo@@v1` is defined in `b.so`. 
According to the original solution, `foo@v1` in `a.o` will be inserted into the symbol map with `key = foo@v1, name = foo`, and `foo@@v1` in `b.so` will be inserted into the symbol map with `key = foo, name = foo`. This causes `foo@@v1` to be cleaned during the `resolve_symbols` phase.
So in [passes.cc#L1229-L1244](https://github.com/rui314/mold/blob/main/elf/passes.cc#L1229-L1244), as `foo` has been cleaned, it cannot match `foo@v1` correctly.

**Comment by rui314** [comment]
This isn't an easy problem, allow me a time to think and experiment.

**Comment by moncefmechri** [comment]
Any luck on this? Can I help in any way?

**Comment by ksco** [comment]
Closed as this is already fixed.

**Pull request closed without merging**
