### PR TITLE
Use `cmake --build` instead of `make` for mimalloc and TBB

### PR DESCRIPTION
**Pull request by IndianBoy42**
This will run whichever build tool was used to generate the cmake project

For example, I set `CMAKE_GENERATOR=Ninja` globally so that cmake will automatically use Ninja always. This would break with the current Makefile as it will try to run make in that directory when there is no Makefile

The only downside is I dont know which cmake version this was added, perhaps its too new, although the project already requires c++20 and some modern tooling

This could be backported to 0.9.1 as well potentially

### CODE REVIEW

**Comment by rui314** [comment]
If the feature might be too new to use, how about adding `-G'Unix Makefiles'` to `cmake` invocation and continue using make? It looks like a simpler solution to me.

**Comment by Alcaro** [comment]
--build is present in [2.8.0](https://cmake.org/cmake/help/v2.8.0/cmake.html#opt%3a--builddir), released November 2009. I think that's old enough.

**Comment by rui314** [comment]
Does `cmake` respect `-j` option passed to its parent `make` process? As long as it works, I don't care too much about how subprojects are built, but it looks like sticking with `make` is simpler. In future, we might want to migrate to `cmake` altogether, and if we do, recursively invoking `cmake --build` would be more appearing.

**Comment by IndianBoy42** [comment]
I don't think by default it does, it just uses nproc internally to find the number of jobs it should use.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by nehaljwani** [comment]
The standard way to pass `-j` to the generator is:
```
cmake --build /path/to/builddir -- -jX <target-name>
```
AFAIK, this would work with both ninja and make. The generator agnostic way to do that is to set `CMAKE_BUILD_PARALLEL_LEVEL` environment variable.

**Comment by rui314** [comment]
So, as I said, I'd like to keep using make and fix the issue by appending `-G'Unix Makefiles'` to the cmake invocations.

**Comment by pseyfert** [comment]
FTR cmake does support `-j` since version 3.12 (nov 2018) https://cmake.org/cmake/help/v3.12/release/3.12.html#id4

**Pull request closed without merging**
