### PR TITLE
tests: come up with common base.sh

### PR DESCRIPTION
**Pull request by marxin**
All tests have a common start, factor it out.

Signed-off-by: Martin Liska <mliska@suse.cz>

### CODE REVIEW

**Comment by marxin** [comment]
Would you be interested in a patch that would do the described refactoring?

**Comment by rui314** [comment]
I kind of like the current way of doing this for a few reasons:

 - it's self-contained, and
 - you can't write lots of code in the boilerplate, so it's guaranteed to be simple.

But I do see the benefit of creating a `base.sh` file, too. Let me think about it.

**Comment by marxin** [comment]
Sure, think about it.

**Review by aminya — APPROVED** [review]

**Comment by rui314** [comment]
I did it in e1275942c8271bafd5e36eeb502295d853d092b8.

**Comment by marxin** [comment]
Oh, great!

**Pull request closed without merging**
