### PR TITLE
tests: print skipped if valgrind is missing

### PR DESCRIPTION
**Pull request by marxin**
Signed-off-by: Martin Liska <mliska@suse.cz>

### CODE REVIEW

**Comment by rui314** [comment]
Is this necessary? Even if valgrind is not available, most tests in this file are not skipped.

**Comment by marxin** [comment]
Yes, otherwise I get:

```
$ ./test/elf/mold-wrapper.sh
Testing mold-wrapper ... abuild@marxinbox:~/rpmbuild/BUILD/mold-1.999.999+git.20220505.ca25f1fd> echo $?
1
```

Which means the tests will fail.

**Comment by rui314** [comment]
Ah, you are right. I'll submit a follow-up patch to suppress the "skipped" message after merging.

**Comment by marxin** [comment]
Thanks, I can confirm it works fine for me now.

**Pull request merged**
