### PR TITLE
[ELF] Add --dy and --dn aliases

### PR DESCRIPTION
**Pull request by Scrumplex**
GNU ld aliases these to `-Bdynamic` and `-Bstatic` respectively.

Signed-off-by: Sefa Eyeoglu <contact@scrumplex.net>

### CODE REVIEW

**Comment by rui314** [comment]
Did you see a program that uses these flags? As far as I tested by building _all_ Gentoo packages, there's literally no program that uses these flags.

**Comment by Scrumplex** [comment]
Only application that I know which uses `-dy` is MakeMKV.

> Did you see a program that uses these flags? As far as I tested by building _all_ Gentoo packages, there's literally no program that uses these flags.

**Comment by rui314** [comment]
OK, I just wanted to know if there's a user of these flags. Merged. Thanks!

**Comment by MaskRay** [comment]
MakeMKV using -dy and -dn doesn't seem like strong justification for adding the options. Can MakeMKV migrate away?

**Pull request merged**
