### PR TITLE
[RISCV] Add global-pointer relaxation for R_RISCV_HI20

### PR DESCRIPTION
**Pull request by ksco**
Related #460

### CODE REVIEW

**Comment by rui314** [comment]
Looks good but I think we need a test for this relaxation.

**Comment by ksco** [comment]
Sure, let's keep this PR open until I added a test for it.

**Comment by rui314** [comment]
Not specific to this particular change, but I'm genuinely curious how much useful the %gp optimization is. It might be useful for small embedded programs, but for usual Unix programs, is it really worth to reserve a register just for enabling this optimization?

**Comment by ksco** [comment]
Yes, it is useful for bare metal programs, but even in a non-embedded environment, the gp register is always occupied and not changed after initialization. Maybe just for the sake of simplicity?

**Comment by ksco** [comment]
This patch is not right, `__global_pointer` is a linker-synthesized symbol, we don't know its value until `fix_synthetic_symbols` is called.

**Pull request closed without merging**
