### PR TITLE
[ELF] Add linker script support to --relocatable

### PR DESCRIPTION
**Pull request by ksco**
This patch doesn't solve #268, but at least made some progress.

### CODE REVIEW

**Comment by ksco** [comment]
Force-pushed to make clang happy.

**Comment by rui314** [comment]
This is again a bit controversial. Our implementation for `-r` is intentionally separated from the main execution passes because `-r` is a very different operation mode than outputting an executable or a shared library. And our linker script implementation is also limited so that the mold is simple and fast. I think we don't want to add more code there unless it is essential.

In this case, they could just pass a list of files instead of a linker script. If they wanted to pass a list of files as a file, they could also use a response file. So I don't think the need is essential.

**Comment by ksco** [comment]
Thanks for the explanation, it makes sense to me. I’ll close this PR now.

**Comment by rui314** [comment]
If you are looking for something to do in this area, you might want to try to build an OS kernel with mold. I don't think you can build the Linux kernel with mold, but for smaller OSes, `--section-start` might be enough.

We want to implement something better than the linker script, but before doing that, we need to understand the existing uses of the script. Trying to link a kernel should give us insights.

**Comment by ksco** [comment]
Thanks for the suggestion, sounds good, I will try to do it.

**Pull request closed without merging**
