### PR TITLE
Fix support for R_RISCV_SET_ULEB128 and R_RISCV_SUB_ULEB128

### PR DESCRIPTION
**Pull request by andreas-schwab**
Handle allocated sections, write the full value into the location and only
write the final value.

### CODE REVIEW

**Comment by rui314** [comment]
How did you verify this fix?

**Comment by andreas-schwab** [comment]
https://build.opensuse.org/package/live_build_log/home:Andreas_Schwab:riscv:mold/mold/standard/riscv64

**Comment by andreas-schwab** [comment]
You cannot write a full address into the location, if it only has enough
room for the difference.

**Comment by rui314** [comment]
I mean, is there any program that you found didn't work without this change?

**Comment by andreas-schwab** [comment]
https://build.opensuse.org/package/live_build_log/devel:gcc:next/mold/openSUSE_Factory_RISCV/riscv64

**Comment by andreas-schwab** [comment]
I was mislead by the brokenness of overwrite_uleb.  The difference will
work out right even without being able to write the full address.

**Comment by rui314** [comment]
Can you read https://github.com/rui314/mold/blob/main/CONTRIBUTING.md and sign your commit?

**Comment by andreas-schwab** [comment]
It is confusing that almost none of the commits are signed.

**Comment by rui314** [comment]
I don't need to sign the contributor agreement that I worded because "I" and "YOU" are the same person, but I want third party contributors to sign.

**Pull request merged**
