### PR TITLE
Fix handling of path buffer sizes

### PR DESCRIPTION
**Pull request by sicherha**
This is a draft pull request that tries to address the concerns raised in #207. I have retained the part of @SvenJo's commit that remains unchanged, and added my suggested overhaul of ` get_current_dir()` and `get_realpath()` as additional commits on top.

@rui314, @SvenJo, please let me know what you think.

### CODE REVIEW

**Comment by rui314** [comment]
It's not your fault, but the APIs of realpath, getcwd, readlink and the like are a bit messy, and that's why I just give a large buffer to the functions so that we can forget about the details (unless a user is trying to use mold with an insanely long pathname). Can we just a buffer with 8192 bytes (which is I believe more than enough, but if not, we can even pass a 16 KiB buffer) so that these functions won't fail?

**Comment by sicherha** [comment]
Wait a second - why don't we simply use the [C++17 filesystem API](https://en.cppreference.com/w/cpp/filesystem)? 💡

**Comment by rui314** [comment]
Indeed this looks better. Thanks!

**Comment by SvenJo** [comment]
I also like the idea of using std::filesystem and concentrating to change  get_current_dir and get_realpath. In my own tests I had trouble to implement the rest of the functions inside  filepath.cc using std::filesystem equivalents. (`path_is_dir` is maybe an easy to convert)

Regards,
Sven

**Comment by rui314** [comment]
I landed a patch to use C++17 filesystem API instead of POSIX API inhttps://github.com/rui314/mold/commit/f6e91df440b387c69a33df71d2a44bac58ad14d0, but had to revert it because it broke many builds. I'll find the cause of the issue, fix it and re-land the patch soon.

**Comment by sicherha** [comment]
Here's the relevant compiler error:
```
In file included from demangle.cc:1:
./mold.h:437:40: error: no member named 'generic_format' in 'std::filesystem::path'
  return {path, std::filesystem::path::generic_format};
                ~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.
```
You may need to replace `std::filesystem::path::generic_format` with `std::filesystem::path::format::generic_format`.

**Comment by sicherha** [comment]
After a bit of code archaeology, here's the explanation: the macOS build image comes with a version of libcxx that was released prior to commit https://github.com/llvm/llvm-project/commit/26005c788b06755ccafe1205de181bbd8b2ed664, which converts the mistaken (overeager) declaration of `enum class format { ...} ;` to the standard-conforming `enum format { ... };`.

**Comment by rui314** [comment]
The problem I was talking about is not about the compilation error on macOS. It started mislinking lots of programs for some reason. I'll investigate, fix it and land it again hopefully soon.

**Pull request merged**
