### PR TITLE
Fix symlinks for absolute `CMAKE_INSTALL_*`

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Related: #738 #846

Signed-off-by: Zhong Ruoyu <zhongruoyu@outlook.com>

### CODE REVIEW

**Comment by rui314** [comment]
Is this a draft?

**Comment by ZhongRuoyu** [comment]
> Is this a draft? Let me know when it's ready for review.

Yes it is. Let me do a little more testing to make sure things work. Sorry it didn't go well last time.

**Comment by ZhongRuoyu** [comment]
Hi @rui314, I've tested some more combinations, and I think this should be working as expected. So I'm marking it as ready for review.

To address the issue better, I have moved the logic for symlink creation to the function `mold_install_relative_symlink(OLD NEW)`. Now, the args `OLD` and `NEW` are both paths relative to the install prefix, unless they are already absolute (which means the `CMAKE_INSTALL_*DIR` must have been set as absolute), in which case they will not be prepended with the prefix.

Special attention to absolute `CMAKE_INSTALL_*DIR` overrides (B2 and B3): in these cases the prefix set during installation `cmake --install <build-dir> --prefix <prefix>` is ignored. Currently I don't have an idea to do anything about this, while keeping everything as simple as it should look. But I'd say it's rather confusing to do this -- normally the install prefix should be a parent directory of `BINDIR`, `MANDIR`, etc. (`DESTDIR` still works, though.)

---

### Without `CMAKE_INSTALL_*` overrides

```
cmake .. -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
```

#### A1. `cmake --install .`
<details> <pre>
root@2994b6bce6ee:~/mold/build# cmake --install .
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/mold/mold-wrapper.so
-- Up-to-date: /usr/local/bin/mold
-- Up-to-date: /usr/local/share/doc/mold/LICENSE
-- Up-to-date: /usr/local/share/man/man1/mold.1
-- Installing symlink: //usr/local/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: //usr/local/bin/ld.mold -> mold
-- Installing symlink: //usr/local/bin/ld64.mold -> mold
-- Installing symlink: //usr/local/share/man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### A2. `cmake --install . --prefix out`
<details> <pre>
root@2994b6bce6ee:~/mold/build# cmake --install . --prefix out
-- Install configuration: "Release"
-- Up-to-date: /root/mold/build/out/lib/mold/mold-wrapper.so
-- Up-to-date: /root/mold/build/out/bin/mold
-- Up-to-date: /root/mold/build/out/share/doc/mold/LICENSE
-- Up-to-date: /root/mold/build/out/share/man/man1/mold.1
-- Installing symlink: //root/mold/build/out/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: //root/mold/build/out/bin/ld.mold -> mold
-- Installing symlink: //root/mold/build/out/bin/ld64.mold -> mold
-- Installing symlink: //root/mold/build/out/share/man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### A3. `cmake --install . --prefix /abs-out`
<details> <pre>
root@2994b6bce6ee:~/mold/build# cmake --install . --prefix /abs-out
-- Install configuration: "Release"
-- Up-to-date: /abs-out/lib/mold/mold-wrapper.so
-- Up-to-date: /abs-out/bin/mold
-- Up-to-date: /abs-out/share/doc/mold/LICENSE
-- Up-to-date: /abs-out/share/man/man1/mold.1
-- Installing symlink: //abs-out/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: //abs-out/bin/ld.mold -> mold
-- Installing symlink: //abs-out/bin/ld64.mold -> mold
-- Installing symlink: //abs-out/share/man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### A4. `DESTDIR=/dest cmake --install . --prefix out`
<details> <pre>
root@2994b6bce6ee:~/mold/build# DESTDIR=/dest cmake --install . --prefix out
-- Install configuration: "Release"
-- Up-to-date: /dest/root/mold/build/out/lib/mold/mold-wrapper.so
-- Up-to-date: /dest/root/mold/build/out/bin/mold
-- Up-to-date: /dest/root/mold/build/out/share/doc/mold/LICENSE
-- Up-to-date: /dest/root/mold/build/out/share/man/man1/mold.1
-- Installing symlink: /dest//root/mold/build/out/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: /dest//root/mold/build/out/bin/ld.mold -> mold
-- Installing symlink: /dest//root/mold/build/out/bin/ld64.mold -> mold
-- Installing symlink: /dest//root/mold/build/out/share/man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### A5. `DESTDIR=/dest cmake --install . --prefix /abs-out`
<details> <pre>
root@2994b6bce6ee:~/mold/build# DESTDIR=/dest cmake --install . --prefix /abs-out
-- Install configuration: "Release"
-- Up-to-date: /dest/abs-out/lib/mold/mold-wrapper.so
-- Up-to-date: /dest/abs-out/bin/mold
-- Up-to-date: /dest/abs-out/share/doc/mold/LICENSE
-- Up-to-date: /dest/abs-out/share/man/man1/mold.1
-- Installing symlink: /dest//abs-out/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: /dest//abs-out/bin/ld.mold -> mold
-- Installing symlink: /dest//abs-out/bin/ld64.mold -> mold
-- Installing symlink: /dest//abs-out/share/man/man1/ld.mold.1 -> mold.1
</pre> </details>

### With `CMAKE_INSTALL_*` overrides (absolute)

Based on what was provided in #738, but with the differences magnified:

```
cmake .. \
  -DCMAKE_C_COMPILER=gcc-10 \
  -DCMAKE_CXX_COMPILER=g++-10 \
  -DCMAKE_INSTALL_BINDIR:PATH=/override-usr/bin \
  -DCMAKE_INSTALL_LIBDIR:PATH=/override-usr/lib \
  -DCMAKE_INSTALL_LIBEXECDIR:PATH=/override-usr/libexec \
  -DCMAKE_INSTALL_DOCDIR:PATH=/override-usr/doc \
  -DCMAKE_INSTALL_MANDIR:PATH=/override-usr/man
```

#### B1. `cmake --install .`
<details> <pre>
root@2994b6bce6ee:~/mold/build1# cmake --install .
-- Install configuration: "Release"
-- Installing: /override-usr/lib/mold/mold-wrapper.so
-- Up-to-date: /override-usr/bin/mold
-- Installing: /override-usr/doc/LICENSE
-- Installing: /override-usr/man/man1/mold.1
-- Installing symlink: //override-usr/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: //override-usr/bin/ld.mold -> mold
-- Installing symlink: //override-usr/bin/ld64.mold -> mold
-- Installing symlink: //override-usr/man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### B2. `cmake --install . --prefix out`
<details> <pre>
root@2994b6bce6ee:~/mold/build1# cmake --install . --prefix out
-- Install configuration: "Release"
-- Up-to-date: /override-usr/lib/mold/mold-wrapper.so
-- Up-to-date: /override-usr/bin/mold
-- Up-to-date: /override-usr/doc/LICENSE
-- Up-to-date: /override-usr/man/man1/mold.1
-- Installing symlink: //override-usr/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: //override-usr/bin/ld.mold -> mold
-- Installing symlink: //override-usr/bin/ld64.mold -> mold
-- Installing symlink: //override-usr/man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### B3. `cmake --install . --prefix /abs-out`
<details> <pre>
root@2994b6bce6ee:~/mold/build1# cmake --install . --prefix /abs-out
-- Install configuration: "Release"
-- Up-to-date: /override-usr/lib/mold/mold-wrapper.so
-- Up-to-date: /override-usr/bin/mold
-- Up-to-date: /override-usr/doc/LICENSE
-- Up-to-date: /override-usr/man/man1/mold.1
-- Installing symlink: //override-usr/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: //override-usr/bin/ld.mold -> mold
-- Installing symlink: //override-usr/bin/ld64.mold -> mold
-- Installing symlink: //override-usr/man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### B4. `DESTDIR=/dest cmake --install . --prefix out`
<details> <pre>
root@2994b6bce6ee:~/mold/build1# DESTDIR=/dest cmake --install . --prefix out
-- Install configuration: "Release"
-- Installing: /dest/override-usr/lib/mold/mold-wrapper.so
-- Installing: /dest/override-usr/bin/mold
-- Set runtime path of "/dest/override-usr/bin/mold" to ""
-- Installing: /dest/override-usr/doc/LICENSE
-- Installing: /dest/override-usr/man/man1/mold.1
-- Installing symlink: /dest//override-usr/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: /dest//override-usr/bin/ld.mold -> mold
-- Installing symlink: /dest//override-usr/bin/ld64.mold -> mold
-- Installing symlink: /dest//override-usr/man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### B5. `DESTDIR=/dest cmake --install . --prefix /abs-out`
<details> <pre>
root@2994b6bce6ee:~/mold/build1# DESTDIR=/dest cmake --install . --prefix /abs-out
-- Install configuration: "Release"
-- Up-to-date: /dest/override-usr/lib/mold/mold-wrapper.so
-- Up-to-date: /dest/override-usr/bin/mold
-- Up-to-date: /dest/override-usr/doc/LICENSE
-- Up-to-date: /dest/override-usr/man/man1/mold.1
-- Installing symlink: /dest//override-usr/libexec/mold/ld -> ../../bin/mold
-- Installing symlink: /dest//override-usr/bin/ld.mold -> mold
-- Installing symlink: /dest//override-usr/bin/ld64.mold -> mold
-- Installing symlink: /dest//override-usr/man/man1/ld.mold.1 -> mold.1
</pre> </details>

### With `CMAKE_INSTALL_*` overrides (relative)

It's getting strange, I'd say. But they now should be correctly handled.

```
cmake .. \
  -DCMAKE_C_COMPILER=gcc-10 \
  -DCMAKE_CXX_COMPILER=g++-10 \
  -DCMAKE_INSTALL_BINDIR:PATH=override-bin \
  -DCMAKE_INSTALL_LIBDIR:PATH=override-lib \
  -DCMAKE_INSTALL_LIBEXECDIR:PATH=override-libexec \
  -DCMAKE_INSTALL_DOCDIR:PATH=override-doc \
  -DCMAKE_INSTALL_MANDIR:PATH=override-man
```

#### C1. `cmake --install .`
<details> <pre>
root@2994b6bce6ee:~/mold/build2# cmake --install .
-- Install configuration: "Release"
-- Up-to-date: /usr/local/override-lib/mold/mold-wrapper.so
-- Up-to-date: /usr/local/override-bin/mold
-- Installing: /usr/local/override-doc/LICENSE
-- Up-to-date: /usr/local/override-man/man1/mold.1
-- Installing symlink: //usr/local/override-libexec/mold/ld -> ../../override-bin/mold
-- Installing symlink: //usr/local/override-bin/ld.mold -> mold
-- Installing symlink: //usr/local/override-bin/ld64.mold -> mold
-- Installing symlink: //usr/local/override-man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### C2. `cmake --install . --prefix out`
<details> <pre>
root@2994b6bce6ee:~/mold/build2# cmake --install . --prefix out
-- Install configuration: "Release"
-- Up-to-date: /root/mold/build2/out/override-lib/mold/mold-wrapper.so
-- Up-to-date: /root/mold/build2/out/override-bin/mold
-- Installing: /root/mold/build2/out/override-doc/LICENSE
-- Up-to-date: /root/mold/build2/out/override-man/man1/mold.1
-- Installing symlink: //root/mold/build2/out/override-libexec/mold/ld -> ../../override-bin/mold
-- Installing symlink: //root/mold/build2/out/override-bin/ld.mold -> mold
-- Installing symlink: //root/mold/build2/out/override-bin/ld64.mold -> mold
-- Installing symlink: //root/mold/build2/out/override-man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### C3. `cmake --install . --prefix /abs-out`
<details> <pre>
root@2994b6bce6ee:~/mold/build2# cmake --install . --prefix /abs-out
-- Install configuration: "Release"
-- Up-to-date: /abs-out/override-lib/mold/mold-wrapper.so
-- Up-to-date: /abs-out/override-bin/mold
-- Installing: /abs-out/override-doc/LICENSE
-- Up-to-date: /abs-out/override-man/man1/mold.1
-- Installing symlink: //abs-out/override-libexec/mold/ld -> ../../override-bin/mold
-- Installing symlink: //abs-out/override-bin/ld.mold -> mold
-- Installing symlink: //abs-out/override-bin/ld64.mold -> mold
-- Installing symlink: //abs-out/override-man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### C4. `DESTDIR=/dest cmake --install . --prefix out`
<details> <pre>
root@2994b6bce6ee:~/mold/build2# DESTDIR=/dest cmake --install . --prefix out
-- Install configuration: "Release"
-- Up-to-date: /dest/root/mold/build2/out/override-lib/mold/mold-wrapper.so
-- Up-to-date: /dest/root/mold/build2/out/override-bin/mold
-- Installing: /dest/root/mold/build2/out/override-doc/LICENSE
-- Up-to-date: /dest/root/mold/build2/out/override-man/man1/mold.1
-- Installing symlink: /dest//root/mold/build2/out/override-libexec/mold/ld -> ../../override-bin/mold
-- Installing symlink: /dest//root/mold/build2/out/override-bin/ld.mold -> mold
-- Installing symlink: /dest//root/mold/build2/out/override-bin/ld64.mold -> mold
-- Installing symlink: /dest//root/mold/build2/out/override-man/man1/ld.mold.1 -> mold.1
</pre> </details>

#### C5. `DESTDIR=/dest cmake --install . --prefix /abs-out`
<details> <pre>
root@2994b6bce6ee:~/mold/build2# DESTDIR=/dest cmake --install . --prefix /abs-out
-- Install configuration: "Release"
-- Up-to-date: /dest/abs-out/override-lib/mold/mold-wrapper.so
-- Up-to-date: /dest/abs-out/override-bin/mold
-- Installing: /dest/abs-out/override-doc/LICENSE
-- Up-to-date: /dest/abs-out/override-man/man1/mold.1
-- Installing symlink: /dest//abs-out/override-libexec/mold/ld -> ../../override-bin/mold
-- Installing symlink: /dest//abs-out/override-bin/ld.mold -> mold
-- Installing symlink: /dest//abs-out/override-bin/ld64.mold -> mold
-- Installing symlink: /dest//abs-out/override-man/man1/ld.mold.1 -> mold.1
</pre> </details>

**Comment by rui314** [comment]
I'd like to hear from @jpalus to make sure if it's OK for sure.

**Comment by jpalus** [comment]
@ZhongRuoyu thanks a lot for figuring it out. Confirmed it works fine for me with absolute paths.

**Comment by ZhongRuoyu** [comment]
Thanks!

**Pull request merged**
