### PR TITLE
Fix Makefile for Termux on Android

### PR DESCRIPTION
**Pull request by joshcangit**
Makefile was installing to nowhere on Termux, Android.
Changed first line to fix this.

### CODE REVIEW

**Comment by rui314** [comment]
Can't you just run `make PREFIX=$PREFIX install` to pass PREFIX?

**Comment by joshcangit** [comment]
I can but I wonder when and why that line was edited from `?=` to `=`?

**Comment by rui314** [comment]
Please see my comment in https://github.com/rui314/mold/pull/300

**Comment by joshcangit** [comment]
I was wondering.
Maybe not just that line but you replaced all the `?=`.
So should I change that to use `ifdef`?
I can do that right now.

**Comment by rui314** [comment]
I made that change so that our Makefile does not inherit variables such as PREFIX, CC, CXX, etc. from the environment. It's intentional. From 1.0.2, please pass PREFIX as `make PREFIX=$PREFIX`.

**Comment by joshcangit** [comment]
Was thinking maybe I want to add checks for directories but then nevermind.
I'm closing this request.

Was also thinking to editing the README.md for this but then I also decided to leave that.
I think it to be a little optional FYI stuff.

**Pull request closed without merging**
