### PR TITLE
Set default CFLAGS and CXXFLAGS values only if they are not already set.

### PR DESCRIPTION
**Pull request by fcambus**
Signed-off-by: Frederic Cambus <fred@statdns.com>

### CODE REVIEW

**Comment by rui314** [comment]
You can set `CFLAGS` and `CXXFLAGS` by passing them as arguments rather than environment variable. E.g. `make CFLAGS=-g`.

**Comment by fcambus** [comment]
I'm aware of this, but why not also allow to pass them as environment variables?

Do you see any drawbacks in doing so?

**Comment by rui314** [comment]
From the point of maintainer's view, making it explicit makes user support easier. Currently, if a user do not explicitly pass CFLAGS or CXXFLAGS, I'm sure no flags are passed. If we accept both environment variables and command line arguments, I have to ensure that the user didn't set a bogus CFLAGS/CXXFLAGS environment variable. So, yes, I saw a drawback in doing this.

**Comment by fcambus** [comment]
Thanks for explaining your rationale. Fine then, closing the issue.

**Pull request closed without merging**
