### PR TITLE
fix minor grammor error in README

### PR DESCRIPTION
**Pull request by vassudanagunta**

### CODE REVIEW

**Comment by 12932** [comment]
dude this isn't a grammatical error, you are just farming commits.

**Comment by vassudanagunta** [comment]
@12932 It is a grammatical error (go ask any native English speaker). I work on the common open source philosophy of "when you see something wrong, fix it."  I think it's pretty crazy that you took the time to comment so rudely and presumptively when this isn't even your repo. 

@rui314, I'm sorry that you took a mean person's word that there isn't a grammatical error.  Too bad. 🤷🏾‍♂️

**Comment by 12932** [comment]
bro you literally spelled grammar incorrectly in the commit

**Comment by rui314** [comment]
Guys, please stop. @vassudanagunta Thank you for your contribution, but I usually do not take a commit that changes a single word if it's minor. I'm not a native speaker and I know this isn't the last error.

**Pull request closed without merging**
