### PR TITLE
[ELF] Add support for more .gnu.note.property variants.

### LINKED ISSUE #824: `.note.gnu.property` not propagated to the output file
I noticed that:

```
$ cat a.c
#include <string.h>

int main(int argc, char **argv)
{
  return strcmp (argv[0], "pes") == 0;
}
$ gcc-12 -c a.c
$ readelf -n a.o

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000020	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA used: 
	x86 feature used: x86
$ gcc-12 a.o -B ~/Programming/mold/objdir
$ readelf -n a.out

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 66687aadf862bd776c8fc18b8e9f8e2008971485

Displaying notes found in: .note.ABI-tag
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0
```

So the note is lost in final executable. Note `ld` and `ld.gold` and `lld` preserve it:

```
$ gcc-12 a.o
$ readelf -n a.out

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000030	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA needed: x86-64-baseline
	x86 feature used: x86
	x86 ISA used: 

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: a9db34a5862eb2791e30343626acd07ba4eeda4a

Displaying notes found in: .note.ABI-tag
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0
$ gcc-12 a.o -fuse-ld=gold
$ readelf -n a.out

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000020	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA needed: x86-64-baseline
	x86 feature used: x86

Displaying notes found in: .note.ABI-tag
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 73066803db6d77cc0512b546d02f1da06f7f62ab

Displaying notes found in: .note.gnu.gold-version
  Owner                Data size 	Description
  GNU                  0x00000009	NT_GNU_GOLD_VERSION (gold version)
    Version: gold 1.16
```

Do I miss something?

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
This makes .gnu.note.property handling generic instead of hardcoded against the
GNU_PROPERTY_X86_FEATURE_1_AND value.
The behavior is based on specification inside GNU gold header comments;
unfortunately a formal document does not exist yet and the comments seem to be
the best reference that can be found.

The support for the actual properties in wild seems scarce; neither gcc nor
clang emits the correct property even when passed -march=x86-64-v3 and using
__builtin_popcnt, for example. Therefore, this does not include a test yet for
the new properties. I'm not sure if we want to resort to [manually written .s files](https://github.com/bminor/binutils-gdb/blob/3451a2d7a3501e9c3fc344cbc4950c495f30c16d/gold/testsuite/gnu_property_b.S)
just for this purpose.

Close #824

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Hm, weird CI failure on Clang only that I can't reproduce locally. I'll keep trying to reproduce.

**Comment by ishitatsuyuki** [comment]
It was actually a legit bug. I'll rewrite the logic to fix it.

**Comment by ishitatsuyuki** [comment]
Should be fixed now. There's quite a bit of open coding, which I need to apologize for being messy, but I don't have a good idea if there's a more simplistic way.

**Comment by rui314** [comment]
Code looks good, but can you add a test?

**Comment by ishitatsuyuki** [comment]
As mentioned in the description, there doesn't seem to be a reliable way to generate this using compiler options. Do you think a .s file is suitable in this case?

**Comment by rui314** [comment]
Sorry I missed that description. I think `.s` is suitable in this case.

**Comment by marxin** [comment]
Good! I've created #885 for documentation improvement .

**Pull request merged**
