### PR TITLE
Windows: define the version of header files to Windows 10

### PR DESCRIPTION
**Pull request by vtorri**
Signed-off-by: Vincent Torri <vtorri@outlook.fr>

### CODE REVIEW

**Comment by rui314** [comment]
What issue does this change fix?

**Comment by vtorri** [comment]
```
C:/Documents/msys2/home/vincent.torri/gitroot_64/mold_vtorri/sha.h:26:3: error: 'BCryptHash' was not declared in this scope; did you mean 'BCryptSignHash'?
```

Reference:

https://docs.microsoft.com/en-us/windows/win32/api/bcrypt/nf-bcrypt-bcrypthash#requirements

this function requires Windows 10

**Comment by rui314** [comment]
I merged your change but reverted since I realized that I didn't understand what this actually was. Sorry.

- Why didn't missing of this preprocessor macro cause an issue with MSVC?
- By defining this macro, what does it actually do? Does it fix the compile error that you presented, or does it turn the compile error into a runtime error?

**Comment by 3rav** [comment]
This change allows you to compile the mold from [56/89] to [78/89], then there is this bug (informatively):

```
if(WIN32)
    target_compile_definitions(mold PRIVATE _WIN32_WINNT=0x0A00)
endif()
```

```
[78/89] Building CXX object CMakeFiles/mold.dir/main.cc.obj
FAILED: CMakeFiles/mold.dir/main.cc.obj
C:\msys64\mingw64\bin\g++.exe -DNOGDI -DNOMINMAX -D_WIN32_WINNT=0x0A00 -DMOLD_VERSION=\"1.4.0\" -IC:/msys64/usr/local/pkg_mold/src/mold-main/third-party/mimalloc/include -IC:/msys64/usr/local/pkg_mold/src/mold-main/third-party/tbb/src/tbb/../../include -march=x86-64 -mtune=generic -O2 -pipe -O2 -g -DNDEBUG -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -std=gnu++20 -MD -MT CMakeFiles/mold.dir/main.cc.obj -MF CMakeFiles\mold.dir\main.cc.obj.d -o CMakeFiles/mold.dir/main.cc.obj -c C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc
In file included from C:/msys64/mingw64/include/windows.h:65,
                 from C:/msys64/usr/local/pkg_mold/src/mold-main/third-party/tbb/include/oneapi/tbb/enumerable_thread_specific.h:39,
                 from C:/msys64/usr/local/pkg_mold/src/mold-main/third-party/tbb/include/tbb/enumerable_thread_specific.h:17,
                 from C:/msys64/usr/local/pkg_mold/src/mold-main/mold.h:24,
                 from C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:1:
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:47:58: error: expected ',' or '...' before '_exception_info'
   47 | static LONG WINAPI vectored_handler(_EXCEPTION_POINTERS *exception_info) {
      |                                                          ^~~~~~~~~~~~~~
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc: In function 'LONG mold::vectored_handler(_EXCEPTION_POINTERS* (*)(_EXCEPTION_POINTERS*))':
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:51:56: error: request for member 'ExceptionRecord' in '* _exception_info', which is of non-class type 'void*()'
   51 |   PEXCEPTION_RECORD exception_record = exception_info->ExceptionRecord;
      |                                                        ^~~~~~~~~~~~~~~
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc: In function 'void mold::install_signal_handler()':
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:66:34: error: invalid conversion from 'LONG (*)(_EXCEPTION_POINTERS* (*)(_EXCEPTION_POINTERS*))' {aka 'long int (*)(_EXCEPTION_POINTERS* (*)(_EXCEPTION_POINTERS*))'} to 'PVECTORED_EXCEPTION_HANDLER' {aka 'long int (*)(_EXCEPTION_POINTERS*)'} [-fpermissive]
   66 |   AddVectoredExceptionHandler(0, vectored_handler);
      |                                  ^~~~~~~~~~~~~~~~
      |                                  |
      |                                  LONG (*)(_EXCEPTION_POINTERS* (*)(_EXCEPTION_POINTERS*)) {aka long int (*)(_EXCEPTION_POINTERS* (*)(_EXCEPTION_POINTERS*))}
In file included from C:/msys64/mingw64/include/winbase.h:16,
                 from C:/msys64/mingw64/include/windows.h:70:
C:/msys64/mingw64/include/errhandlingapi.h:25:99: note:   initializing argument 2 of 'void* AddVectoredExceptionHandler(ULONG, PVECTORED_EXCEPTION_HANDLER)'
   25 |     WINBASEAPI PVOID WINAPI AddVectoredExceptionHandler (ULONG First, PVECTORED_EXCEPTION_HANDLER Handler);
      |                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
[79/89] Building CXX object CMakeFiles/mold.dir/macho/output-chunks.cc.obj
[80/89] Building CXX object CMakeFiles/mold.dir/macho/main.cc.obj
[81/89] Building CXX object CMakeFiles/mold.dir/multi-glob.cc.obj
[82/89] Building CXX object CMakeFiles/mold.dir/elf/output-chunks.cc.obj
[83/89] Building CXX object CMakeFiles/mold.dir/elf/passes.cc.obj
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by vtorri** [comment]
> I merged your change but reverted since I realized that I didn't understand what this actually was. Sorry.
> 
>     * Why didn't missing of this preprocessor macro cause an issue with MSVC?

maybe cmake is adding it, but anyway, mold does not compile with Visual Studio... (I just tried)

>     * By defining this macro, what does it actually do? Does it fix the compile error that you presented, or does it turn the compile error into a runtime error?

see https://github.com/rui314/mold/commit/76f6959a8ec72b74f26c9eabcdf78934e344ced9#commitcomment-81197726

**Comment by rui314** [comment]
mold does compile with Visual Studio with Clang. Modern MSVC comes with Clang, so we are using it to compile mold.

**Comment by vtorri** [comment]
you are using a compiler provided by llvm/clang (-T clangcl). It certainly uses clang-cll.exe as compiler.

I've looked at the Visual Studio solution that cmake is creating, and it  has set to 10 the version of the SDK. That's why there is no error with BCryptHash() function, I think.

**Comment by rui314** [comment]
Before doing any more work for mingw, I'd like to evaluate the value of doing it, given that MSVC/Clang can be used to build mold. MSVC/Clang is the first-party developer tool for Windows. It's free of charge. I do not see an immediate benefit of compiling mold with mingw. I genuinely wonder why people wanted to build mold with mingw. Do you mind if I ask you guys to explain a little bit more about the motivation?

**Comment by vtorri** [comment]
@rui314 
 * gcc on Windows may produce faster binaries than msvc. As the purpose of mold is being fast, that could be interesting to check.
 * gcc can find errors that another compiler does not (i experienced the contrary with libdwarf, where I contribute : msvc cl.exe compiler found errors that gcc didn't report). I also experienced this with the suncc compiler when i ported some libs to the old OpenSolaris.

**Comment by rui314** [comment]
Again, we are using clang on Windows. Its output should be as good as gcc's output.

As to the second point, we already use gcc and clang to build mold on Unix, and most error should be caught there. If there's an issue that occurs only on Windows which clang-cl cannot find but gcc, that's genuinely a new finding, but I don't think that scenario is very convincing.

**Comment by 3rav** [comment]
After switching to clang:

```
==> Starting build()...
-- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
```

errors occurs:

```
[77/89] Building CXX object CMakeFiles/mold.dir/main.cc.obj
FAILED: CMakeFiles/mold.dir/main.cc.obj
C:\msys64\mingw64\bin\clang++.exe -DNOGDI -DNOMINMAX -DMOLD_VERSION=\"1.4.0\" -IC:/msys64/usr/local/pkg_mold/src/mold-main/third-party/mimalloc/include -IC:/msys64/usr/local/pkg_mold/src/mold-main/third-party/tbb/src/tbb/../../include -march=x86-64 -mtune=generic -O2 -pipe -O2 -g -DNDEBUG -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -std=gnu++20 -MD -MT CMakeFiles/mold.dir/main.cc.obj -MF CMakeFiles\mold.dir\main.cc.obj.d -o CMakeFiles/mold.dir/main.cc.obj -c C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:47:58: error: expected ')'
static LONG WINAPI vectored_handler(_EXCEPTION_POINTERS *exception_info) {
                                                         ^
C:/msys64/mingw64/include/excpt.h:53:54: note: expanded from macro 'exception_info'
#define exception_info (struct _EXCEPTION_POINTERS *)_exception_info
                                                     ^
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:47:36: note: to match this '('
static LONG WINAPI vectored_handler(_EXCEPTION_POINTERS *exception_info) {
                                   ^
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:51:54: error: member reference base type 'void *() __attribute__((cdecl))' is not a structure or union
  PEXCEPTION_RECORD exception_record = exception_info->ExceptionRecord;
                                       ~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:51:21: error: cannot initialize a variable of type 'PEXCEPTION_RECORD' (aka '_EXCEPTION_RECORD *') with an rvalue of type 'struct _EXCEPTION_POINTERS *'
  PEXCEPTION_RECORD exception_record = exception_info->ExceptionRecord;
                    ^                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:66:3: error: no matching function for call to 'AddVectoredExceptionHandler'
  AddVectoredExceptionHandler(0, vectored_handler);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/errhandlingapi.h:25:29: note: candidate function not viable: no known conversion from 'LONG (_EXCEPTION_POINTERS *(*)(struct _EXCEPTION_POINTERS *))' (aka 'long (_EXCEPTION_POINTERS *(*)(struct _EXCEPTION_POINTERS *))') to 'PVECTORED_EXCEPTION_HANDLER' (aka 'long (*)(_EXCEPTION_POINTERS *)') for 2nd argument
    WINBASEAPI PVOID WINAPI AddVectoredExceptionHandler (ULONG First, PVECTORED_EXCEPTION_HANDLER Handler);
                            ^
4 errors generated.
[78/89] Building CXX object CMakeFiles/mold.dir/macho/tapi.cc.obj
```

**Comment by vtorri** [comment]
@3rav please open a NEW issue about that error

**Pull request merged**
