### PR TITLE
[RISCV] Relax AUIPC+JALR to C.JAL or C.J

### PR DESCRIPTION
**Pull request by ksco**
This patch completes the R_RISCV_CALL_PLT relaxation function, as it is done in [LLVM lld](https://github.com/llvm/llvm-project/blob/main/lld/ELF/Arch/RISCV.cpp#L554). However, I don't know if there is any case where auipc+jalr can be relaxed to c.j.

### CODE REVIEW

**Comment by ksco** [comment]
I forgot to add Signed-off-by, force-pushed.

**Comment by rui314** [comment]
I think it's a bit risky to work on optional relaxations at the moment. We should focus on making RV32 work first, shouldn't we?

**Comment by ksco** [comment]
RV32 has been adapted to existing tests, just like RV64. But I haven't tried compiling any serious programs, and yes, I think you're right.

So, what should I do next if I want to make RV32 production-ready?

**Comment by ksco** [comment]
Btw, `auipc+jalr -> c.j` can happens in tail call optimization.

**Comment by rui314** [comment]
Do all tests pass? If so, the next step would be to set up a CI.

**Comment by ksco** [comment]
```
sysroot-linker-script.sh
sysroot.sh
sysroot2.sh
```

These still fail due to [this](https://github.com/rui314/mold/pull/670#issuecomment-1229282925), but I think it has something to do with GCC, not mold. It seems that this issue is similar to https://github.com/rui314/mold/issues/358. riscv64-gcc has fixed it, but it seems riscv32-gcc still has it.

**Comment by rui314** [comment]
That's a great news! I didn't know that our RV32 support works that well. Did you have any idea as to how to set up a CI?

**Comment by ksco** [comment]
Yeah, I didn't expect it to be this smooth at first! 😄

Currently, Ubuntu does not provide the `gcc-10-riscv32-linux-gnu` package. I think we can use pre-built binaries from riscv-gnu-toolchain like [this one](https://github.com/riscv-collab/riscv-gnu-toolchain/releases/tag/2022.08.26#:~:text=riscv32%2Dglibc%2Dubuntu%2D20.04%2Dnightly%2D2022.08.26%2Dnightly.tar.gz).

But the sysroot-related cases don't seem to pass the test, unfortunately.

**Comment by rui314** [comment]
How about writing a script like this and place it in `$PATH` as riscv32-linux-gnu-gcc?

```
#!/bin/bash
/absolute/path/to/riscv32-linux-unknown-gcc -L /usr/riscv32-linux-gnu "$@"
```

**Comment by rui314** [comment]
You may also want to add a new CMake option `MOLD_ENABLE_RV32_QEMU_TESTS` to enable tests with qemu-riscv32. By default, we don't want to run them even if `MOLD_ENABLE_QEMU_TESTS` is `ON`, as they don't run correctly in most environments at the moment.

**Comment by ksco** [comment]
> How about writing a script like this and place it in `$PATH` as riscv32-linux-gnu-gcc?
> 
> ```
> #!/bin/bash
> /absolute/path/to/riscv32-linux-unknown-gcc -L /usr/riscv32-linux-gnu "$@"
> ```

Looks great to me ;)

**Comment by ksco** [comment]
> You may also want to add a new CMake option `MOLD_ENABLE_RV32_QEMU_TESTS` to enable tests with qemu-riscv32. By default, we don't want to run them even if `MOLD_ENABLE_QEMU_TESTS` is `ON`, as they don't run correctly in most environments at the moment.

Okay, I'll do that in a separate PR.

**Comment by ksco** [comment]
Hi, Rui,

Do you have time to add RV32 to CI? I can also try to do this.

**Comment by rui314** [comment]
I added RV32 to CI, and all the tests are green!

**Comment by ksco** [comment]
🎉

**Comment by rui314** [comment]
Is this true you can relax `AUIPC+JALR` to `C.J`? `C.J` is just a jump instruction and not jump-and-link-register instruction, no?

**Comment by rui314** [comment]
My bad, `C.J` is defined as `jal x0, offset[11:1]`.

**Comment by ksco** [comment]
It can happen with tail call optimization. I'm going to write a test case to cover this situation, but I'm not quite sure if this test is necessary for ARM and X86.

**Comment by rui314** [comment]
At this point you probably want to try to link a large program like mold itself or even gcc using mold. It's amazing that we get to this point so quickly.

**Pull request merged**
